module.exports = {
    env: {
        browser: true,
        es2021: true,
        node: true,
    },
    extends: [
        "eslint:recommended",
        "@banjoanton/eslint-config-prettier",
        "plugin:unicorn/recommended",
        "plugin:import/recommended",
        "plugin:promise/recommended",
        "plugin:n/recommended",
        "plugin:@typescript-eslint/recommended",
    ],
    parser: "@typescript-eslint/parser",
    plugins: [
        "@typescript-eslint",
        "unicorn",
        "import",
        "promise",
        "unused-imports",
        "json",
        "banjo",
    ],
    parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
    },
    settings: {
        "import/resolver": {
            typescript: true,
            node: true,
        },
    },
    ignorePatterns: [
        "node_modules",
        "dist",
        "build",
        "coverage",
        "libby",
        ".github",
        ".*",
        "*.md",
    ],
    rules: {
        // typescript
        "no-unused-vars": "off",
        "@typescript-eslint/no-unused-vars": "warn",
        "@typescript-eslint/ban-ts-comment": "off",
        "@typescript-eslint/no-empty-function": "off",
        "@typescript-eslint/no-namespace": "off",
        // eslint
        camelcase: ["warn", { properties: "never" }],
        "consistent-return": "off",
        "require-await": "off",
        "array-callback-return": "warn",
        "no-constant-condition": "warn",
        "no-duplicate-imports": "warn",
        "object-shorthand": "warn",
        "arrow-body-style": "warn",
        "no-unmodified-loop-condition": "warn",
        "no-use-before-define": [
            "error",
            {
                functions: false,
                classes: false,
                variables: true,
                allowNamedExports: false,
            },
        ],
        "require-atomic-updates": "warn",
        complexity: ["warn", 15],
        "dot-notation": "warn",
        eqeqeq: ["error", "always"],
        "max-params": ["error", 3],
        "no-else-return": "warn",
        "no-empty-function": "off",
        "no-lonely-if": "warn",
        "no-multi-assign": "warn",
        "no-nested-ternary": "error",
        "no-shadow": "warn",
        "no-unneeded-ternary": "warn",
        "no-useless-rename": "warn",
        "no-var": "error",
        "no-useless-return": "warn",
        "prefer-arrow-callback": "warn",
        "prefer-const": "warn",
        "prefer-template": "warn",
        "sort-imports": [
            "warn",
            {
                ignoreCase: true,
                ignoreDeclarationSort: true,
                ignoreMemberSort: false,
                memberSyntaxSortOrder: ["none", "all", "multiple", "single"],
            },
        ],
        "spaced-comment": ["warn", "always", { markers: ["/"] }],
        // unicorn
        "unicorn/no-null": "off",
        "unicorn/no-process-exit": "off",
        "unicorn/filename-case": [
            "error",
            {
                cases: {
                    camelCase: true,
                    pascalCase: true,
                    kebabCase: true,
                    snakeCase: false,
                },
            },
        ],
        "unicorn/prefer-ternary": "off",
        "unicorn/prevent-abbreviations": "off",
        "unicorn/prefer-module": "off",
        "unicorn/prefer-top-level-await": "off",
        "unicorn/no-useless-undefined": "off",
        "unicorn/consistent-function-scoping": "off",
        "unicorn/no-array-reduce": "warn",
        "unicorn/no-array-callback-reference": "off",
        // import
        "import/named": "off",
        "import/no-unresolved": "off",
        // n
        "n/no-missing-import": "off",
        "n/no-unsupported-features/es-syntax": "off",
        "n/no-process-exit": "off",
        "n/shebang": "off",
        "n/no-unpublished-import": "off",
        "n/no-unsupported-features/node-builtins": "off",
        // banjo
        "banjo/module-exports": "error",
        "banjo/one-line-if": "off",
        // promise
        "promise/always-return": "off",
        "no-unused-vars": "off",
    },
    overrides: [
        {
            files: [".*.js", "*config.js"],
            rules: {
                "unicorn/prefer-module": "off",
                "banjo/module-exports": "error",
            },
        },
    ],
};
